Move migrators to the context, so they can be configured.
Jumoo/uSyncMigrations pull request #38
Opened 2022-11-23 09:42 UTC by KevinJump

Move Migrators to the context, - so they can be configured by a profile. 

Idea is you can have all the migrators loaded, and then have the profiles decide which ones to use, eg. grid -> grid or grid -> blocklist. 

.eg 

you might go something like this in your `ISyncMigrationProfile`

```cs
Migrators = _migrators.GetDefault().Replace<GridMigrator>(typeof(GridToBlockListMigrator)); 
```
(n.b I am making the syntax up as a i go in this PR)

need to think of the best way to present this to people, but also the best way to work out programmatically which migrator is the 'default' so when we say get us all the migrators with no config, we get the right ones.

2022-11-24 10:49 UTC, leekelleher approved these changes
@KevinJump I'm happy with the approach using profiles. 👍 

Would the original approach still work? e.g. inside a `Composer` class...

```csharp
builder
    .SyncPropertyMigrators()
        .Replace<GridMigrator, GridToBlockListMigrator>()
;
```
...or would that be defunct now?

2022-11-24 10:49 UTC, leekelleher commented on uSync.Migrations/Composing/SyncPropertyMigratorCollectionBuilder.cs
> +    public IList<ISyncPropertyMigrator> GetDefaultMigrators()
Umbraco has a concept of using `DefaultPropertyValueConverter` attribute to distinguish between the Core and custom value-converters. Could do similar?
e.g. https://github.com/umbraco/Umbraco-CMS/blob/release-10.3.2/src/Umbraco.Core/PropertyEditors/PropertyValueConverterCollection.cs#L31

2022-11-24 10:49 UTC, leekelleher commented on uSync.Migrations/Handlers/DataTypeMigrationHandler.cs
> +                if (!options.Migrators.Any(x => x.Editors.InvariantContains(editorAlias)))
Small note, this is now a loop, were it was previously a dictionary key lookup.
Not a big performance hit, more an observation. 👀

2022-11-28 09:29 UTC, KevinJump commented on uSync.Migrations/Composing/SyncPropertyMigratorCollectionBuilder.cs
> +    public IList<ISyncPropertyMigrator> GetDefaultMigrators()
yeah - i started down that route (didn't know they did it in core) with a `SyncDefaultMigrator` attribute- but i was unsure, now I know it's 'core approved' I might do that 😄

2022-11-28 09:30 UTC, KevinJump commented on uSync.Migrations/Handlers/DataTypeMigrationHandler.cs
> +                if (!options.Migrators.Any(x => x.Editors.InvariantContains(editorAlias)))
yeah hopefully this isn't to much of a performance hit - the underling thing is a list, (so not renumerating) - also likely quite 'small' on the grand scale of things.

2022-11-28 09:42 UTC, KevinJump commented on uSync.Migrations/Composing/SyncPropertyMigratorCollectionBuilder.cs
> +    public IList<ISyncPropertyMigrator> GetDefaultMigrators()
Actually i remember now, I don't want just 'default' attributed ones, if a community migrator exists it sort of becomes the default' its only when there are two or more for the same attribute that i need to resolve one of them as default. 

Thinking about this from a developer point of view, if developer A makes a migrator and developer B also makes one for the same thing, they could a) - both mark them as default, or b) both mark them as secondary, 

Locally for them it would all 'work' but if someone installed both it would throw a wobbler :( - 

In the code we could object and throw - but then there wouldn't be a way for the person with both of these items installed to fix the problem. - Maybe we should warn people, and then say you need to remove one of the conflicting items in a composer (so we would be back to the 'standard' route you are using @leekelleher ) 

But if we want to resolve this via UI, i think we have to load them all, and then let the user choose which one they want, maybe not letting a migration happen until you have chosen your preference (either in the UI or via a ISyncProfile). 

*thinking out Loud

2022-12-05 11:55 UTC, KevinJump commented
I have tidied this up and changed it to be simpler (hopefully). 

Now a `ISyncMigrationProfile` can signify which editors it prefers 

```cs
// for this migrator we want to use our special grid migrator.
PreferedMigrators = new Dictionary<string, string>()
{
    { Umbraco.Cms.Core.Constants.PropertyEditors.Aliases.Grid, typeof(GridToBlockListMigrator).Name }
},
```

and this will win.

you can also define a 'default' if you want -  and that will be the next choice.

```cs
[SyncMigrator(Umbraco.Cms.Core.Constants.PropertyEditors.Aliases.Grid)]
[SyncDefaultMigrator]
internal class GridToBlockListMigrator : SyncPropertyMigratorBase
{
```

if nothing is prefered or 'default' then the interface will throw a validation error

![image](https://user-images.githubusercontent.com/431231/205631415-37eae235-6886-4b07-b75f-a27cb82ae877.png)

next step will be to somehow let people choose a default via the UI when they get this error. (but not for this PR)

2022-12-05 11:58 UTC, KevinJump commented
Notes for this : 

- The Replace method will still work fine. 
- Nothing should use the Migrator collection during the migration, the service loads the selected migrators into the context and that is where they are referenced from (might make it internal?)
- You can still break things by having multiple 'defaults' for the same editor.

2022-12-05 12:00 UTC, merged

2022-12-05 12:01 UTC, leekelleher requested changes
Code wise, all looking good to me!
Spotted a couple of minor things, left comments inline.

2022-12-05 12:01 UTC, leekelleher commented on uSync.Migrations/Configuration/Models/MigrationOptions.cs
> +    public IDictionary<string, string> PreferedMigrators { get; set; }
Spotted typo: `PreferedMigrators` => `PreferredMigrators`.
I'm happy to submit a PR.

2022-12-05 13:23 UTC, KevinJump commented
Picking up the spellings now, turns out i can't spell preferred (it still looks wrong!)

2022-12-05 13:33 UTC, KevinJump commented on uSync.Migrations/Composing/SyncPropertyMigratorCollectionBuilder.cs
> +    public IList<ISyncPropertyMigrator> GetDefaultMigrators()
Just resolving this, `replace` isn't defunct if you don't want it to be.

the new methods look at all loaded PropertyMigrators and where there might be two for the same editor, it looks for a preferred one in the options or one with a `[SyncDefaultMigrator]` value.

if after that there are duplicates you get a validation error. 

but if you replace an editor with another one in a composer, it will bypass most of this because there will be no duplicates then. 

the advantage of the preferred/default is it means we can have different profiles use different mappers (or have it in the UI). but you might not want/need that, and `replace` still works as expected.